### ISSUE TITLE
Add pre-massaged data into jinja/jq context when generating registry

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#204]
When generating code, in many cases the JQ part would be similar between different languages. 

It particular:

1. grouping attributes by the root namespace (note: `id` of the group in the registry is not always accurate - only the attribute name is ). 
  
    Here's the JQ
    ```jq
    .groups
    | map(select(.type == "attribute_group"))
    | map(select(.id | startswith("registry")))
    | map({attributes: .attributes
        | map(.group_id= (if .name |index(".") then .name |split(".")[0] else "other" end))
    })
    | [.[].attributes[] ]
    | group_by(.group_id)
    | map({ id: .[0].group_id, attributes: [.[]] })
    ```
    
    It can be implemented once in rust and appear in the Jinja context as an additional `ctx.grouped_attributes` property - nobody would need to write and debug it again.
    
    Same with metrics, events, etc.

2. Implement the outcome of https://github.com/open-telemetry/semantic-conventions/issues/1118
  
    E.g. Option 3.5 implementation looks like
    
    ```jq
    | map({
      id: .id,
      attributes: .attributes
        | map(if has("deprecated") then . else . + {"deprecated": null} end)
        | group_by(.const_name)
        | map({const_name: .[0].const_name, names: [.[]] | sort_by(.deprecated) })
        | map(.names[0]),
    ```
    I'm not sure how far we can go there, but it could be that `ctx.grouped_attributes` from p1 above provides all the default behavior we want codegen to follow and resolves collisions in a common way. Someone can still use raw `groups` and massage data with JQ if they want to.

3. Minor: sort attributes in `ctx.grouped_attributes` by name. Requirement level does not appear in attribute definitions code, sorting by requirement level does not make sense there. If someone needs to sort differently, they still could

Ideal outcome would be that language SIGs won't need to write any JQ and would only do something complicated to implement non-standard behavior.

As a first step, it'd be great to reduce https://github.com/lmolkova/opentelemetry-python/blob/5d151671ff9ad5ecb20c507ddfe64684a46aa6c6/scripts/semconv/templates/registry/weaver.yaml#L1-L31 to something like

```yaml
params:
  excluded: ["ios", "aspnetcore", "signalr", "android", "dotnet", "jvm", "kestrel"]
  stable_package_name: opentelemetry.semconv


templates:
  - pattern: semantic_attributes.j2
    filter: >
      .grouped_attributes
     # filter based on stability - could be more convenient
      | map(select(if $filter == "any" then true else .stability == $filter end)) }) 
     # filter based on excluded namespaces - could be more convenient
      | map(select(.root_namespace as $id | any( $excluded[]; . == $id) | not )) 
      | map(select(.attributes | length > 0))
      | map({
        root_namespace,
        attributes,
        output: $output + "attributes/",
        stable_package_name: $stable_package_name + ".attributes",
        filter: $filter
      })
```
