### ISSUE TITLE
JQ errors are suppressed

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#264]
JQ errors are ignored during registry generation / markdown update.

**To Reproduce**

1. Define a `weaver.yaml` like 

  ```yaml
    - pattern: readme.md.j2
      filter: 'error("foo")' # or do something that'd result in JQ error
     ...
  ```
  (e.g. change one in semconv  https://github.com/open-telemetry/semantic-conventions/blob/a44ff768718b6e82f2dea42189ba14712c795e6b/templates/registry/markdown/weaver.yaml)

2. Run generation 

**Expected behavior**

- registry generation fails. 
- JQ error is propagated in the output
- generation stops

**Actual behavior**

- original groups are passed to jinja as if there was no JQ filter
- generation continues and fails later in jinja templates (if JQ modified the structure) or results in incorrect data (if structure is the same, but filters didn't run),
