### ISSUE TITLE
Add support for a `params` section per template

### ISSUE THREAD

**Issue by lquerel** [open-telemetry/weaver#288]
It’s not uncommon to have the same template applied with a different JQ filter and a different name for the generated file. Having the ability to specify a set of parameters per template specification in the weaver.yaml configuration file would be helpful. Today, it’s possible to simulate that by adding a projection in the JQ filter to include this information, but it’s not obvious and not necessarily easy to understand.

```yaml
params:
  excluded_attributes: ["messaging.client_id"]

templates:
  - pattern: "attributes.ts"
    filter: semconv_attributes({"exclude_stability": ["experimental"]})
    params:
      file_name: "stable_attributes.ts"
    application_mode: single
  - pattern: "attributes.ts"
    filter: semconv_attributes({"exclude_stability": ["stable"]})
    params:
      file_name: "experimental_attributes.ts"
    application_mode: single
```
