### ISSUE TITLE
`semconv_grouped_metrics` group by root namespace uses group.id instead of metric_name to determine root namespace

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#289]
Try excluding v8js namespace 

```yaml
params:
  excluded_namespaces: [v8js]

templates:
  - pattern: semantic_metrics.j2
    filter: >
      semconv_grouped_metrics({
        "exclude_root_namespace": $excluded_namespaces
      })
```

As a result, v8js metrics will be generated in the file `veightjs` - since that's what is used in the group name.

### Workaround

use `excluded_namespaces: [v8js, veightjs]`

(`v8js` is still needed because for attribute, root namespace is determined correctly)

**Expected behavior**
Group ID is not used to determine root namespace

**Additional context**
https://github.com/open-telemetry/semantic-conventions/pull/1314
