### ISSUE TITLE
Semconv schema: don't require attributes on metrics

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#405]
Json schema validation shows error when metrics is defined without attributes
<img width="356" alt="image" src="https://github.com/open-telemetry/weaver/assets/2347409/4648ec97-c6b8-4d7b-8f65-9458c02e2189">

with `Missing property "attributes".yaml-schema: https://raw.githubusercontent.com/open-telemetry/build-tools/v0.24.0/semantic-conventions/semconv.schema.json`

Metrics don't have to have attributes or may inherit them through extension mechanism.

**Comment by jerbly** [comment]
@lmolkova @jsuereth - I'm happy to take this one on if you would like to assign it to me. It's similar to a PR I just did for group stability: https://github.com/open-telemetry/weaver/pull/467

I will change the EBNF and json schema. However, there is currently a difference in this area between the EBNF and the schema. The EBNF currently defines `attributes` as mandatory for all group types and `extends` optional. Whereas the schema defines `attributes` and `extends` with an `anyOf` meaning it's valid to omit `attributes` provided you have `extends` instead. There's currently one single non-metric defined with `extends` and without `attributes`:

```yaml
  - id: span.db.client
    type: span
    stability: experimental
    brief: This span defines the attributes used to perform database client calls.
    span_kind: client
    extends: trace.db.common.full
```
Is this a valid case? If so the EBNF should be defined like this `( extends | attributes | ( extends attributes ) )`.
