### ISSUE TITLE
Allow updating enum values when referencing attribute

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#479]
Semantic conventions that reference a common attribute with an enum type, should be able to extend/overwrite the list of possible values. 

E.g.

```yaml
- id: http.request.method
  type:
    allow_custom_values: true
    members:
      - id: delete
        value: "DELETE"
        brief: 'DELETE method.'
      - id: get
        value: "GET"
        brief: 'GET method.'
...

- ref: http.request.method
  type:
    allow_custom_values: true
    members:
      - id: purge
        value: "PURGE"
        brief: 'non-standard PURGE method.'
```

currently redeclaring a type is not supported. 

While additional values could be documented in the note, md generation adds another note with possible values according to enum.

Related: https://github.com/open-telemetry/semantic-conventions/pull/205

**Comment by lmolkova** [comment]
I like the proposal!

I couple of concerns/open questions around additional members:
- Codegen and resolved schema: how would we generate `HttpRequestMethodEnum`? Is it a union of all possible values across all references? A new refined enum type for this specific reference? Ignore refined type in the codegen?
  - I think we should eventually be able to generate a new enum for each refined type - we'd need at least a consistent naming pattern for the refined type and maybe some jinja helper from weaver in the future. 
- do we allow to remove additional_members? Probably no.  Deprecate them? - probably yes. Do they have stability? - ?

**Comment by jerbly** [comment]
This is not in the title of this issue "Allow updating enum values when referencing attribute", and maybe there are no instances in the otel semconvs right now, but in private company-wide registries I have had:
1. An enum type in more than one attribute e.g. a `state` enum and two attributes `app.current_state`, `app.next_state`.
2. An array where the members are the enum type, e.g. `states[]`

Decoupling the enum type from the attribute would allow more usage patterns. This was mentioned [here](https://github.com/open-telemetry/weaver/issues/479#issuecomment-2504241884)

**Comment by trisch-me** [comment]
> An enum type in more than one attribute e.g. a state enum and two attributes app.current_state, app.next_state.
@jerbly is it similar to the changes we need for `cpu.state`? see this [comment](https://github.com/open-telemetry/weaver/issues/479#issuecomment-2504241957) where we have an enum which should be used in multiple attributes

**Comment by trisch-me** [comment]
Generic problem statement:

- we need to be able to reuse existing enums without the need to repeat all it’s values every time. It is possible right now with just a ref
- we need to be able to add new fields to existing enums while referencing them. This could be done in 2 ways - if particular attribute will be used in more than 1 place - add it to the parent enum. If this attributes is very specific to particular case - we might allow to add it to the current usage only
- we need to be able to remove some values from base enum / use only specific values while referencing attribute. Right now it’s not enforced and `note` section provides which members should be used

Instead of removing attributes from base enumeration I propose to be more verbose and provide a set of selected attributes instead, omitting not needed.

Taking @jsuereth’s example it could be done in following way

base example
```yaml
- id: registry.http
- attributes:
  - id: http.request.method # base enum
    type:
      members:
        -id: head
        -id: delete
        -id: get
        -id: post
```

Formal definition:

``` yaml
- id: <attribute-id>
  - ref: <base-enum-id>             # Reuse the existing enum as is
    - enum_refinement:                 # new, optional
      - selected_members:            # new, which base entries to keep, if skipped all members are used, optional
        - ref: <member-id>           # (each refers to a member of base enum)
        - ref: <member-id>
        …
    - additional_members:            # new, context-specific enum entries, optional
      - id: <new-member-id>
        value: “some value"
        brief: "description of the new member"
    
      - id: <new-member-id>  
        value: “some value 2"
        brief: “description"
```
-------
when `enum_refinement` is omitted -  the attribute simply reuses the full base-enum, so following enum will have all 4 values `head`, `delete`, `get` and `post`

```yaml
- id: http.common
  - attributes:
    - ref: http.request.method
```
-------
when `selected_members` is present - weaver will drop all base members except exactly those named here. So the enum will have only 2 members in following example: `get` and `post`

```yaml
- id: http.common
- attributes:
  - ref: http.request.method
    - enum_refinement:                 
      - selected_members: 
        - id: get
        - id: post
```
-------
when `additional_members ` is present - in addition to selected base members enum will get these new members with their own id and value. In following case enum will have 3 members: `get`, `post`, `patch`

```yaml
- id: http.common
- attributes:
  - ref: http.request.method
    - enum_refinement:                 
      - selected_members: 
        - id: get
        - id: post
      - additional_members:
        - id: patch
          value “PATCH"
```
-------
if `selected_members ` are skipped but `additional_members` are there we are only adding new members specific to the current enum, so in this case we will have 5 items in enum: `head`, `delete`, `get` and `post` and new `put`. 

```yaml
- id: http.common
- attributes:
  - ref: http.request.method
    - enum_refinement:                 
      - additional_members:
        - id: put
          value “PUT"
```

**Comment by jerbly** [comment]
Yes. We should add enums to the type system rather than having them as part of the definition of an attribute.

**Comment by trisch-me** [comment]
During one of the past meetings we have discussed that we should split this issue into 2:

- in most of the existing cases we use only one value from the enum (i.e. db.name), we could probably replace it with static const value. From examples I have checked in semconv metrics it seems not straightforward, i.e. we define parent metric with the field (`hw.type`, `db.system.name`) and then use it in particular metrics via extend mechanism. So we would need to find an option to redefine it in derived metric, if we proceed with this option.

- there are few options where we need to extend an enum for specific case (i.e. `cpu.mode`), right now registry enum contains all possible fields and restriction is applied through a note in every usage `note: "Following states SHOULD be used: `user`, `system`, `kernel`”`. For those we could proceed with maybe only extension to make things simple?

please let me know your thoughts.

**Comment by thompson-tomo** [comment]
I have found a way to address 1 via annotations as a starting point. Would be good to get feedback on https://github.com/open-telemetry/semantic-conventions/pull/2739

**Comment by thompson-tomo** [comment]
So just to share my thoughts on addressing constants ie rpc.system/db.system.name. 

Would be if we could define a package of signals for instance "rpc client" which contains the corresponding signals of a rpc client (span, events & metrics as per #872. This package could then be used by an implementation ie gRPC client. This implementation allows for all instances of an attribute to be updated with new brief, a required value etc. For an example of an implementation see #803

**Comment by thompson-tomo** [comment]
The solution above works ok for spans however I am failing to see how it can work for metrics & events which we currently can't even workaround. If the above could would work for those other signals it would however lead to significant growth in the definitions needing to be maintained. 

Let's use db client as an example, if each signal has the db system name (which it should) we have 12 signals (metrics & spans). As the definition is per db system the definition qty is multipled by the number of systems documented which is 14, so 168 definitions are needing to be maintained. So the summary would be:
- 12 base definitions
- 168 system speecific definitions
- 180 total

Now let's recalculate using packages and implementations:
- 12 base definitions
- 1 package
- 14 implementations which says update attributes used in the package with the following info
- 27 total

At the end of the schema resolution you end up with the same definitions but significantly less input definitions.

**Comment by thompson-tomo** [comment]
Now let's think about types what I forsee is something like the below

Unresolved:
```
types:
  name: foo.bar.type
  values:
    - name: foo
      value: foo
    - name: bar
      value: bar
    - name: baz
      value: baz
attributes:
  - key: foo.bar
    type: foo.bar.type
spans:
  - type: foo.client
     ...
    attributes:
      - ref: foo.bar
        required_value: foo
```

Then after resolution we get out:

```
types:
  name: foo.bar.type
  values:
    - name: foo
      value: foo
    - name: bar
      value: bar
    - name: baz
      value: baz
attributes:
  - key: foo.bar
    type: foo.bar.type
spans:
  - type: foo.client
     ...
    attributes:
      - name: foo.bar
        type: foo.bar.type
          value_kind: string
          required_value: foo
```

For scenarios where we need a subset of the values the best solution I can think of is would be to allow changing the type of an attribute if the original type uses the new type. So something like:
```
types:
  name: foo.bar.sub
  values:
    - name: foo
      value: foo

  name: foo.bar.type
  uses:
    - foo.bar.sub
  values:
    - name: bar
      value: bar
    - name: baz
      value: baz
```

**Comment by lmolkova** [comment]
it's orthogonal to metrics/events problem.  we should have `metric_ref` and `event_ref` and `span_ref` allowing to refine spans. Relevant https://github.com/open-telemetry/semantic-conventions/issues/592.

With resuable/shared attribute groups (https://github.com/open-telemetry/weaver/issues/824#issuecomment-3242861532) the duplication is minimized. 

---------------

It's not clear how to evolve syntax like

```yaml
spans:
  - type: foo.client
     ...
    attributes:
      - name: foo.bar
        type: foo.bar.type
          value_kind: string
          required_value: foo
```

there are other types of enum refinement discussed in this issue. We don't have to implement them right away, but we should have extension mechanism in place to support them in the future without breaking anyone. Hence we need different types of refinements (`literal`, `extension`, `etc`) and different set of properties depending on that type.
