### ISSUE TITLE
Require attributes and event fields to have stability

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#564]
See https://github.com/open-telemetry/semantic-conventions/issues/1777 - we don't validate that stability is present on attributes or event fields

**Comment by jerbly** [comment]
@lmolkova looks like we're also not enforcing `stability` on enum members of event fields: https://github.com/open-telemetry/semantic-conventions/blob/main/model/device/events.yaml#L36 

I assume we want this fixed too?

**Comment by lmolkova** [comment]
@jerbly great catch! yes, explicit stability everywhere it matters is the goal :)

**Comment by jerbly** [comment]
At the moment the Weaver code, EBNF and semconv.schema.json all define the `body` of the event as an `any_value`. Some `any_value`s can contain `any_value`s. Therefore the `body` itself is required to have `stability` defined. This is missing in every use of `body` in the current semconvs.
```yaml
    body:
      id: device_lifecycle_state
      type: map
      requirement_level: required
      stability: experimental # <-------------- This is also required
      fields:
        - id: ios.state
          stability: experimental
          type: enum
          ...
```
