### ISSUE TITLE
Weaver 0.13.* drops original `deprecated` string value

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#599]
We now completely drop the original deprecated: `{string value}`.

Here's the original attribute definition

```yaml
- id: k8s.pod.labels
  brief: "Deprecated, use `k8s.pod.label` instead."
  deprecated: "Replaced by `k8s.pod.label`."
```

Here's a resolved definition:

```yaml
- name: k8s.pod.labels
  brief: Deprecated, use `k8s.pod.label` instead.
  deprecated:
    reason: obsoleted
```

We can, of course, update all semconv to populate new structured thing, but all/most of the codegen uses the value of deprecated  thing.

Weaver should provide `deprecated_note` (or similar) filter and default to old string description - this is for back-compat and a convenience for the future.

Here's the best we can do in semconv https://github.com/open-telemetry/semantic-conventions/pull/1902 - fallback to attribute brief which is not the same as the original deprecated value.
