### ISSUE TITLE
Support deprecated struct on enum members

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#672]
Tried using `deprecated` struct on enum members and got

```yaml
- id: coldfusion
  value: "coldfusion"
  deprecated:
    reason: obsoleted
```

```
Diagnostic report:

  × The semantic convention spec is invalid (path_or_url: "/home/
  │ weaver/source/database/deprecated/registry-deprecated.yaml").
  │ groups[0].attributes: data did not match any variant of untagged enum
  │ AttributeSpec at line 9 column 7
```
