### ISSUE TITLE
Check that semconv referenced in `renamed_to` exists

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#673]
Let's say I write

```yaml
  - id: code.filepath
    stability: development
    ....
    deprecated:
      reason: renamed
      renamed_to: does.not.exist # this one does not exist
```

I don't get any error from the weaver, so I added a semconv policy into https://github.com/open-telemetry/semantic-conventions/pull/2047, which checks that:

1. there is an attribute (metric/event/etc depending on what's deprecated) with this identity
2. it's not deprecated

p2 is probably a preference and belongs in the semconv policy, but the p1 seems to belong in the weaver resolution process. We should try resolving it similarly to `ref` or `extends` and fail if it's not found.

So I think we should have p1 is weaver
