### ISSUE TITLE
Change template type examples to use a key-value structure

### ISSUE THREAD

**Issue by jerbly** [open-telemetry/weaver#747]
https://github.com/open-telemetry/semantic-conventions/issues/1740 was solved by simplifying the examples. Type safety was established by making the example type match the inner template type with #710. However, we would like to improve the example structure to allow the definition of key-value pairs like so:

```yaml
groups:
  - id: rpc.connect_rpc.request.metadata
    type: template[string[]]
    examples:
      - key: "my-custom-metadata-attribute"
        value: ["1.2.3.4", "1.2.3.5"]
  - id: db.elasticsearch.path_parts
    type: template[any]
    examples:
      - key: "index"
        value: "test-index"
      - key: "doc_id"
        value: 123
```
