### ISSUE TITLE
Dual registry resolves incorrectly

### ISSUE THREAD

**Issue by jerbly** [open-telemetry/weaver#750]
**Describe the bug**
The resolver returns strange results with duplicated and/or missing attributes. Tested with the released version 0.15.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `weaver registry resolve -r data/multi-registry/custom_registry`
2. Note the incorrect resolved output:
```yaml
groups:
- id: shared.attributes
  type: attribute_group
  brief: Attributes shared between our signals.
  attributes:
  - name: error.type
    type: string
    brief: The error type.
    examples: Ex
    requirement_level: required
    stability: stable
  - name: auction.name
    type: string
    brief: |
      The name of the auction
    examples:
    - Fish for sale
    requirement_level: recommended
    stability: stable
  span_kind: null
  events: []
  metric_name: null
  instrument: null
  unit: null
  name: null
  lineage:
    provenance:
      registry_id: acme
      path: data/multi-registry/custom_registry/custom_registry.yaml
- id: metric.auction.bid.count
  type: metric
  brief: Count of all bids we've seen
  stability: stable
  attributes:
  - name: auction.name
    type: string
    brief: |
      The name of the auction
    examples:
    - Fish for sale
    requirement_level: recommended
    stability: stable
  - name: auction.id
    type: int
    brief: |
      The id of the auction.
    requirement_level: recommended
    stability: stable
  - name: auction.id
    type: int
    brief: |
      The id of the auction.
    requirement_level: required
    stability: stable
  span_kind: null
  events: []
  metric_name: auction.bid.count
  instrument: counter
  unit: '{bid}'
  name: null
  lineage:
    provenance:
      registry_id: acme
      path: data/multi-registry/custom_registry/custom_registry.yaml
    attributes:
      auction.id:
        source_group: shared.attributes
        inherited_fields:
        - brief
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
      auction.name:
        source_group: shared.attributes
        inherited_fields:
        - brief
        - examples
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
      error.type:
        source_group: otel.registry
        inherited_fields:
        - brief
        - examples
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
``` 

**Expected behavior**
In the attribute_group and metric it should have: `error.type`, `auction.id` and `auction.name`. Instead we're missing `auction.id` from the attribute_group and we have `auction.id` duplicated in the metric and `error.type` is missing! Note that the `test_multi_registry()` unit test is passing.
