### ISSUE TITLE
Weaver registry diff: template extension weirdness

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#760]
Take a look at the https://github.com/open-telemetry/semantic-conventions/pull/2307

it has

```
schema-diff/
  ansi/
    schema-diff.j2
    weaver.yaml
```

I run 

```ps
weaver registry diff -r  https://github.com/open-telemetry/semantic-conventions/archive/refs/tags/v1.34.0.zip[model] \
  --baseline-registry https://github.com/open-telemetry/semantic-conventions/archive/refs/tags/v1.33.0.zip[model] \
  --diff-template .\internal\tools\scripts\schema-diff\ --diff-format ansi -o diff-output
```

and things work fine, I get something like
```yaml
    all:
      changes:
        - rename_attributes:
            attribute_map:
              code.column: code.column.number
              code.filepath: code.file.path
              ...
```
in output file.

Now, if I rename `schema-diff.j2` -> `schema-diff.yaml.j2` (and also change file name in the config), I'll get

```yaml
""
    all:
      changes:
        - rename_attributes:
            attribute_map:
              "code.column": "code.column.number"
              "code.filepath": "code.file.path"
              ...
```
(Note all the quotes)

It also reproduces with `--diff-format yaml` and corresponding folder structure.
It seems there is some escaping(?) magic that tries to be helpful based on the file extension, but it gets in the way.
