### ISSUE TITLE
weaver registry diff: old_name is a group id and not a metric/event name

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#776]
Run 

```bash
weaver.exe registry diff -r .\model --baseline-registry https://github.com/open-telemetry/semantic-conventions/archive/refs/tags/v1.34.0.zip[model] --diff-template .\internal\tools\scripts\schema-diff\ --diff-format yaml
```

on semconv main.

Result

```yaml
...
changes:
  events: []
  metrics:
  - name: metric.k8s.container.status.reason
    type: added
  - new_name: system.cpu.time
    note: Replaced by `system.cpu.time`.
    old_name: metric.cpu.time
    type: renamed
  - new_name: system.cpu.utilization
    note: Replaced by `system.cpu.utilization`.
    old_name: metric.cpu.utilization
    type: renamed
...
```

expected
```yaml
...
changes:
  events: []
  metrics:
  - name: k8s.container.status.reason
    type: added
  - new_name: system.cpu.time
    note: Replaced by `system.cpu.time`.
    old_name: cpu.time
    type: renamed
  - new_name: system.cpu.utilization
    note: Replaced by `system.cpu.utilization`.
    old_name: cpu.utilization
    type: renamed
...
```
