### ISSUE TITLE
generate does not have access to group annotations

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/weaver#788]
**Describe the bug**
The group annotations are not passed to the group object used in code generation.

**To Reproduce**
Create a group such as:
```
groups:
  - id: file.mtime
    type: metric
    metric_name: file.mtime
    stability: beta
    brief: "Elapsed time since the last modification of the file or folder, in seconds since Epoch."
    instrument: updowncounter
    unit: "s"
    annotations:
      scraper:
        enabled: true
```

Use this group to generate code such as:
```
{% for m in ctx.groups | selectattr("type", "equalto", "metric") %}  {{ m.id | safe }}:
    description: {{ m.brief | safe }}
    enabled: {{ m.annotations.scraper.enabled }}
    {% if m.instrument == "updowncounter" %}sum:
      monotonic: false
      aggregation_temporality: cumulative
      value_type: int
    {% else %}gauge:
      value_type: int
    {% endif %}unit: {{ m.unit }}
{% if m.attributes %}    attributes:{% for attr in m.attributes %}
      - {{ attr.name | safe }}{% endfor %}
{% endif %}{% endfor %}
```

**Expected behavior**
The code should generate without problems.

**Actual behavior**
The code fails to generate with
```
Diagnostic report:

  × Template evaluation error -> undefined value (in metadata.yaml.j2:27)
  │ 

```

**Additional context**

It appears the issue is tied to how we pass the data to the ResolvedGroup struct:
https://github.com/open-telemetry/weaver/blob/main/crates/weaver_forge/src/registry.rs#L147-L167
